// Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_LOCKUP_SUCCESS = 'USER_LOCKUP_SUCCESS';

// Special
export const GET_SPECIAL_SUCCESS = 'GET_SPECIAL_SUCCESS';
export const DELETE_SPECIAL_SUCCESS = 'DELETE_SPECIAL_SUCCESS';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';

// Blog

export const GET_POSTS_LIST = "GET_POSTS_LIST";